spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/number
    driverClassName: org.postgresql.Driver
    username: number
    password: number
    hikari:
      maximum-pool-size: 5

camunda.bpm.admin-user:
  id: demo
  password: demo