spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bpm
    driverClassName: org.postgresql.Driver
    username: bpm
    password: bpm
    hikari:
      maximum-pool-size: 5

camunda.bpm.admin-user:
  id: demo
  password: demo